# Generated by Django 2.2.14 on 2020-10-31 09:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dating', '0002_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.CharField(max_length=20)),
                ('unread_message_count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_profile', to='dating.Profile')),
                ('chat_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_recipient', to='dating.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(max_length=500, null=True, verbose_name='Message')),
                ('created', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.Chat')),
            ],
        ),
    ]
