# Generated by Django 2.2.14 on 2020-10-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_outbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(default='test', max_length=500, verbose_name='Message'),
            preserve_default=False,
        ),
    ]
