# Generated by Django 2.2.14 on 2020-10-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20201031_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='chat',
            name='preview',
            field=models.CharField(max_length=50),
        ),
    ]
