# Generated by Django 2.2.14 on 2020-10-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20201031_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='preview',
            field=models.CharField(max_length=60),
        ),
    ]
