# Generated by Django 2.2.14 on 2020-11-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_auto_20201031_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='preview',
            field=models.CharField(max_length=20),
        ),
    ]
