# Generated by Django 2.2.14 on 2020-10-30 21:32

import dating.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_number', models.CharField(default=dating.models.profile_id_generator, max_length=10, unique=True)),
                ('age', models.IntegerField()),
                ('friends', models.ManyToManyField(blank=True, to='dating.Profile')),
            ],
        ),
    ]
