# Generated by Django 2.2.14 on 2020-10-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unread_message_count',
            field=models.IntegerField(default=0),
        ),
    ]
